from pydantic import BaseModel, Field


class ResponseSchema(BaseModel):
    """
    Schema for the response from the support agent.
    """

    customer_id: str = Field(..., description="The unique identifier for the customer.")
    response: str = Field(..., description="The response generated by the support agent.")
    tools_used: list[str] = Field(..., description="List of tools used to generate the response.")